export const initialData = {
  medList: {
    'med-1': { id: "m-0", content: "weichkapsel_transparent", amount:""},
    'med-2': { id: "m-1", content: "weichkapsel_braun", amount:""},
    'med-3': { id: "m-2", content: "kapsel_weiss_gelb_orange", amount:""},
    'med-4': { id: "m-3", content: "kapsel_weiss_gelb", amount:""},
    'med-5': { id: "m-4", content: "kapsel_weiss", amount:""},
    'med-6': { id: "m-5", content: "dragee_blau", amount:""},
    'med-7': { id: "m-6", content: "dragee_pink", amount:""},
    'med-8': { id: "m-7", content: "tablette_beige_oval", amount:""},
    'med-9': { id: "m-8", content: "tablette_weiss_oval", amount:""},
    'med-10': { id: "m-9", content: "tablette_braun_rund", amount:""},
    'med-11': { id: "m-10", content: "tablette_blau_rund", amount:""},
    'med-12': { id: "m-11", content: "tablette_weiss_zink", amount:""},
    'med-13': { id: "m-12", content: "tablette_weiss_10mm", amount:""},
    'med-14': { id: "m-13", content: "tablette_weiss_8mm", amount:""},
    'med-15': { id: "m-14", content: "tablette_weiss_7mm", amount:""},
  },
  box1: {
    'med-1': { id: "b1-0", content: "weichkapsel_transparent", amount:1},
    'med-2': { id: "b1-1", content: "weichkapsel_braun", amount:1},
    'med-3': { id: "b1-2", content: "kapsel_weiss_gelb_orange",amount:1},
    'med-4': { id: "b1-3", content: "kapsel_weiss_gelb", amount:1},
    'med-5': { id: "b1-4", content: "kapsel_weiss", amount:1},
    'med-6': { id: "b1-5", content: "dragee_blau", amount:1},
    'med-7': { id: "b1-6", content: "dragee_pink", amount:1},
    'med-8': { id: "b1-7", content: "tablette_beige_oval", amount:1},
    'med-9': { id: "b1-8", content: "tablette_weiss_oval", amount:1},
    'med-10': { id: "b1-9", content: "tablette_braun_rund", amount:1},
    'med-11': { id: "b1-10", content: "tablette_blau_rund", amount:1},
    'med-12': { id: "b1-11", content: "tablette_weiss_zink", amount:1},
    'med-13': { id: "b1-12", content: "tablette_weiss_10mm", amount:1},
    'med-14': { id: "b1-13", content: "tablette_weiss_8mm", amount:1},
    'med-15': { id: "b1-14", content: "tablette_weiss_7mm", amount:1},
  },
  box2: {
    'med-1': { id: "b2-0", content: "weichkapsel_transparent", amount:1},
    'med-2': { id: "b2-1", content: "weichkapsel_braun", amount:1},
    'med-3': { id: "b2-2", content: "kapsel_weiss_gelb_orange",amount:1},
    'med-4': { id: "b2-3", content: "kapsel_weiss_gelb", amount:1},
    'med-5': { id: "b2-4", content: "kapsel_weiss", amount:1},
    'med-6': { id: "b2-5", content: "dragee_blau", amount:1},
    'med-7': { id: "b2-6", content: "dragee_pink", amount:1},
    'med-8': { id: "b2-7", content: "tablette_beige_oval", amount:1},
    'med-9': { id: "b2-8", content: "tablette_weiss_oval", amount:1},
    'med-10': { id: "b2-9", content: "tablette_braun_rund", amount:1},
    'med-11': { id: "b2-10", content: "tablette_blau_rund", amount:1},
    'med-12': { id: "b2-11", content: "tablette_weiss_zink", amount:1},
    'med-13': { id: "b2-12", content: "tablette_weiss_10mm", amount:1},
    'med-14': { id: "b2-13", content: "tablette_weiss_8mm", amount:1},
    'med-15': { id: "b2-14", content: "tablette_weiss_7mm", amount:1},
  },
  box3: {
    'med-1': { id: "b3-0", content: "weichkapsel_transparent", amount:1},
    'med-2': { id: "b3-1", content: "weichkapsel_braun", amount:1},
    'med-3': { id: "b3-2", content: "kapsel_weiss_gelb_orange",amount:1},
    'med-4': { id: "b3-3", content: "kapsel_weiss_gelb", amount:1},
    'med-5': { id: "b3-4", content: "kapsel_weiss", amount:1},
    'med-6': { id: "b3-5", content: "dragee_blau", amount:1},
    'med-7': { id: "b3-6", content: "dragee_pink", amount:1},
    'med-8': { id: "b3-7", content: "tablette_beige_oval", amount:1},
    'med-9': { id: "b3-8", content: "tablette_weiss_oval", amount:1},
    'med-10': { id: "b3-9", content: "tablette_braun_rund", amount:1},
    'med-11': { id: "b3-10", content: "tablette_blau_rund", amount:1},
    'med-12': { id: "b3-11", content: "tablette_weiss_zink", amount:1},
    'med-13': { id: "b3-12", content: "tablette_weiss_10mm", amount:1},
    'med-14': { id: "b3-13", content: "tablette_weiss_8mm", amount:1},
    'med-15': { id: "b3-14", content: "tablette_weiss_7mm", amount:1},
  },
  box4: {
    'med-1': { id: "b4-0", content: "weichkapsel_transparent", amount:1},
    'med-2': { id: "b4-1", content: "weichkapsel_braun", amount:1},
    'med-3': { id: "b4-2", content: "kapsel_weiss_gelb_orange",amount:1},
    'med-4': { id: "b4-3", content: "kapsel_weiss_gelb", amount:1},
    'med-5': { id: "b4-4", content: "kapsel_weiss", amount:1},
    'med-6': { id: "b4-5", content: "dragee_blau", amount:1},
    'med-7': { id: "b4-6", content: "dragee_pink", amount:1},
    'med-8': { id: "b4-7", content: "tablette_beige_oval", amount:1},
    'med-9': { id: "b4-8", content: "tablette_weiss_oval", amount:1},
    'med-10': { id: "b4-9", content: "tablette_braun_rund", amount:1},
    'med-11': { id: "b4-10", content: "tablette_blau_rund", amount:1},
    'med-12': { id: "b4-11", content: "tablette_weiss_zink", amount:1},
    'med-13': { id: "b4-12", content: "tablette_weiss_10mm", amount:1},
    'med-14': { id: "b4-13", content: "tablette_weiss_8mm", amount:1},
    'med-15': { id: "b4-14", content: "tablette_weiss_7mm", amount:1},
  },
  box5: {
    'med-1': { id: "b5-0", content: "weichkapsel_transparent", amount:1},
    'med-2': { id: "b5-1", content: "weichkapsel_braun", amount:1},
    'med-3': { id: "b5-2", content: "kapsel_weiss_gelb_orange",amount:1},
    'med-4': { id: "b5-3", content: "kapsel_weiss_gelb", amount:1},
    'med-5': { id: "b5-4", content: "kapsel_weiss", amount:1},
    'med-6': { id: "b5-5", content: "dragee_blau", amount:1},
    'med-7': { id: "b5-6", content: "dragee_pink", amount:1},
    'med-8': { id: "b5-7", content: "tablette_beige_oval", amount:1},
    'med-9': { id: "b5-8", content: "tablette_weiss_oval", amount:1},
    'med-10': { id: "b5-9", content: "tablette_braun_rund", amount:1},
    'med-11': { id: "b5-10", content: "tablette_blau_rund", amount:1},
    'med-12': { id: "b5-11", content: "tablette_weiss_zink", amount:1},
    'med-13': { id: "b5-12", content: "tablette_weiss_10mm", amount:1},
    'med-14': { id: "b5-13", content: "tablette_weiss_8mm", amount:1},
    'med-15': { id: "b5-14", content: "tablette_weiss_7mm", amount:1},
  },
  columns: {
    'column-1': {
      id: 'column-1',
      title: 'Med List',
      taskIds: ['med-1', 'med-2', 'med-3', 'med-4', 'med-5', 'med-6', 'med-7', 'med-8', 'med-9', 'med-10', 'med-11', 'med-12', 'med-13', 'med-14', 'med-15'],
    },
    'column-2': {
      id: 'column-2',
      data: 'box1',
      title: 'Med Box 1',
      taskIds: [],
    },
    'column-3': {
      id: 'column-3',
      data: 'box2',
      title: 'Med Box 2',
      taskIds: [],
    },
    'column-4': {
      id: 'column-4',
      data: 'box3',
      title: 'Med Box 3',
      taskIds: [],
    },
    'column-5': {
      id: 'column-5',
      data: 'box4',
      title: 'Med Box 4',
      taskIds: [],
    },
    'column-6': {
      id: 'column-6',
      data: 'box5',
      title: 'Med Box 5',
      taskIds: [],
    },
  },
  // Facilitate reordering of the columns
  columnOrder: ['column-2', 'column-3', 'column-4', 'column-5', 'column-6'],
  columnMed: ['column-1'],
};

export const saved_data = {
  'column-2': {
    id: 'column-2',
    taskIds: [],
  },
  'column-3': {
    id: 'column-3',
    taskIds: [],
  },
  'column-4': {
    id: 'column-4',
    taskIds: [],
  },
  'column-5': {
    id: 'column-5',
    taskIds: [],
  },
  'column-6': {
    id: 'column-6',
    taskIds: [],
  }
};
