export const initialData = {
  tasks: {
    'task-1': { id: 'task-1', content: "weichkapsel_transparent", amount:""},
    'task-2': { id: 'task-2', content: "weichkapsel_braun", amount:""},
    'task-3': { id: 'task-3', content: "kapsel_weiss_gelb_orange", amount:""},
    'task-4': { id: 'task-4', content: "kapsel_weiss_gelb", amount:""},
    'task-5': { id: 'task-5', content: "kapsel_weiss", amount:""},
    'task-6': { id: 'task-6', content: "dragee_blau", amount:""},
    'task-7': { id: 'task-7', content: "dragee_pink", amount:""},
    'task-8': { id: 'task-8', content: "tablette_beige_oval", amount:""},
    'task-9': { id: 'task-9', content: "tablette_weiss_oval", amount:""},
    'task-10': { id: 'task-10', content: "tablette_braun_rund", amount:""},
    'task-11': { id: 'task-11', content: "tablette_blau_rund", amount:""},
    'task-12': { id: 'task-12', content: "tablette_weiss_zink", amount:""},
  },
  tasks1: {
    'task-1': { id: 'm1task-1', content: "weichkapsel_transparent", amount:1},
    'task-2': { id: 'm1task-2', content: "weichkapsel_braun", amount:1},
    'task-3': { id: 'm1task-3', content: "kapsel_weiss_gelb_orange",amount:1},
    'task-4': { id: 'm1task-4', content: "kapsel_weiss_gelb", amount:1},
    'task-5': { id: 'm1task-5', content: "kapsel_weiss", amount:1},
    'task-6': { id: 'm1task-6', content: "dragee_blau", amount:1},
    'task-7': { id: 'm1task-7', content: "dragee_pink", amount:1},
    'task-8': { id: 'm1task-8', content: "tablette_beige_oval", amount:1},
    'task-9': { id: 'm1task-9', content: "tablette_weiss_oval", amount:1},
    'task-10': { id: 'm1task-10', content: "tablette_braun_rund", amount:1},
    'task-11': { id: 'm1task-11', content: "tablette_blau_rund", amount:1},
    'task-12': { id: 'm1task-12', content: "tablette_weiss_zink", amount:1},
  },
  tasks2: {
    'task-1': { id: 'm1task-1', content: "weichkapsel_transparent", amount:1},
    'task-2': { id: 'm1task-2', content: "weichkapsel_braun", amount:1},
    'task-3': { id: 'm1task-3', content: "kapsel_weiss_gelb_orange",amount:1},
    'task-4': { id: 'm1task-4', content: "kapsel_weiss_gelb", amount:1},
    'task-5': { id: 'm1task-5', content: "kapsel_weiss", amount:1},
    'task-6': { id: 'm1task-6', content: "dragee_blau", amount:1},
    'task-7': { id: 'm1task-7', content: "dragee_pink", amount:1},
    'task-8': { id: 'm1task-8', content: "tablette_beige_oval", amount:1},
    'task-9': { id: 'm1task-9', content: "tablette_weiss_oval", amount:1},
    'task-10': { id: 'm1task-10', content: "tablette_braun_rund", amount:1},
    'task-11': { id: 'm1task-11', content: "tablette_blau_rund", amount:1},
    'task-12': { id: 'm1task-12', content: "tablette_weiss_zink", amount:1},
  },
  tasks3: {
    'task-1': { id: 'm1task-1', content: "weichkapsel_transparent", amount:1},
    'task-2': { id: 'm1task-2', content: "weichkapsel_braun", amount:1},
    'task-3': { id: 'm1task-3', content: "kapsel_weiss_gelb_orange",amount:1},
    'task-4': { id: 'm1task-4', content: "kapsel_weiss_gelb", amount:1},
    'task-5': { id: 'm1task-5', content: "kapsel_weiss", amount:1},
    'task-6': { id: 'm1task-6', content: "dragee_blau", amount:1},
    'task-7': { id: 'm1task-7', content: "dragee_pink", amount:1},
    'task-8': { id: 'm1task-8', content: "tablette_beige_oval", amount:1},
    'task-9': { id: 'm1task-9', content: "tablette_weiss_oval", amount:1},
    'task-10': { id: 'm1task-10', content: "tablette_braun_rund", amount:1},
    'task-11': { id: 'm1task-11', content: "tablette_blau_rund", amount:1},
    'task-12': { id: 'm1task-12', content: "tablette_weiss_zink", amount:1},
  },
  tasks4: {
    'task-1': { id: 'm1task-1', content: "weichkapsel_transparent", amount:1},
    'task-2': { id: 'm1task-2', content: "weichkapsel_braun", amount:1},
    'task-3': { id: 'm1task-3', content: "kapsel_weiss_gelb_orange",amount:1},
    'task-4': { id: 'm1task-4', content: "kapsel_weiss_gelb", amount:1},
    'task-5': { id: 'm1task-5', content: "kapsel_weiss", amount:1},
    'task-6': { id: 'm1task-6', content: "dragee_blau", amount:1},
    'task-7': { id: 'm1task-7', content: "dragee_pink", amount:1},
    'task-8': { id: 'm1task-8', content: "tablette_beige_oval", amount:1},
    'task-9': { id: 'm1task-9', content: "tablette_weiss_oval", amount:1},
    'task-10': { id: 'm1task-10', content: "tablette_braun_rund", amount:1},
    'task-11': { id: 'm1task-11', content: "tablette_blau_rund", amount:1},
    'task-12': { id: 'm1task-12', content: "tablette_weiss_zink", amount:1},
  },
  tasks5: {
    'task-1': { id: 'm1task-1', content: "weichkapsel_transparent", amount:1},
    'task-2': { id: 'm1task-2', content: "weichkapsel_braun", amount:1},
    'task-3': { id: 'm1task-3', content: "kapsel_weiss_gelb_orange",amount:1},
    'task-4': { id: 'm1task-4', content: "kapsel_weiss_gelb", amount:1},
    'task-5': { id: 'm1task-5', content: "kapsel_weiss", amount:1},
    'task-6': { id: 'm1task-6', content: "dragee_blau", amount:1},
    'task-7': { id: 'm1task-7', content: "dragee_pink", amount:1},
    'task-8': { id: 'm1task-8', content: "tablette_beige_oval", amount:1},
    'task-9': { id: 'm1task-9', content: "tablette_weiss_oval", amount:1},
    'task-10': { id: 'm1task-10', content: "tablette_braun_rund", amount:1},
    'task-11': { id: 'm1task-11', content: "tablette_blau_rund", amount:1},
    'task-12': { id: 'm1task-12', content: "tablette_weiss_zink", amount:1},
  },
  columns: {
    'column-1': {
      id: 'column-1',
      title: 'Med List',
      taskIds: ['task-1', 'task-2', 'task-3', 'task-4', 'task-5', 'task-6', 'task-7', 'task-8', 'task-9', 'task-10', 'task-11', 'task-12'],
    },
    'column-2': {
      id: 'column-2',
      data: 'tasks1',
      title: 'Med Box 1',
      taskIds: [],
    },
    'column-3': {
      id: 'column-3',
      data: 'tasks2',
      title: 'Med Box 2',
      taskIds: [],
    },
    'column-4': {
      id: 'column-4',
      data: 'tasks3',
      title: 'Med Box 3',
      taskIds: [],
    },
    'column-5': {
      id: 'column-5',
      data: 'tasks4',
      title: 'Med Box 4',
      taskIds: [],
    },
    'column-6': {
      id: 'column-6',
      data: 'tasks5',
      title: 'Med Box 5',
      taskIds: [],
    },
  },
  // Facilitate reordering of the columns
  columnOrder: ['column-2', 'column-3', 'column-4', 'column-5', 'column-6'],
  columnMed: ['column-1'],
};

export const saved_data = {
  'column-2': {
    id: 'column-2',
    taskIds: [],
  },
  'column-3': {
    id: 'column-3',
    taskIds: [],
  },
  'column-4': {
    id: 'column-4',
    taskIds: [],
  },
  'column-5': {
    id: 'column-5',
    taskIds: [],
  },
  'column-6': {
    id: 'column-6',
    taskIds: [],
  }
};
